version: '3.5'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: [ "./main" ]
        ports:
            - 8080:8080
        restart: always
